fix(buckets): run core.ps1 for `$scoopdir`
CI tests were failing due to $bucketsdir resolving to "D:\buckets"

> Describing Test-UpdateStatus
> Error: [-] Describe Test-UpdateStatus failed
> Message
>  ItemNotFoundException: Cannot find path 'D:\buckets' because it does not exist.
>  at Get-LocalBucket, D:\a\ScoopInstaller.Scoop\ScoopInstaller.Scoop\lib\buckets.ps1:61
>  at <ScriptBlock>, D:\a\ScoopInstaller.Scoop\ScoopInstaller.Scoop\libexec\scoop-status.ps1:38
>  at <ScriptBlock>, D:\a\ScoopInstaller.Scoop\ScoopInstaller.Scoop\test\Scoop-Status.Tests.ps1:33